# Site settings
name: EBI Jekyll Boilerplate
group: EMBL-EBI Web Development
email: noreply@ebi.ac.uk
domain: //ebiwd.github.io
baseurl: /EBI-Boilerplate-Jekyll
permalink: pretty

# Build settings
markdown: kramdown
