name: EBI Jekyll Boilerplate
email: noreply@ebi.ac.uk
markdown: kramdown
domain: //ebiwd.github.io
baseurl: /EBI-Boilerplate-Jekyll
permalink: /EBI-Boilerplate-Jekyll/updates/:year/:month/:day/:title
